services:
  - type: web
    name: springboot-backend
    env: java
    region: oregon
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    javaVersion: 17
